name: 'Integration'

on:
  pull_request:
    branches:
      - 'main'
      - 'release'
      - 'develop'

jobs:
  check-integration:
    name: Check before Integration

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Eslint check
        run: npm run lint

      - name: Type check
        run: |
          npm run typecheck
           echo "> Type checking passed"

      - name: Unit test
        run: npm run test

      - name: build result to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
