name: 'PULL REQUEST NOTIFICATION'

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'main'

jobs:
  NOTIFICATION:
    if: "!contains(github.event.pull_request.title , 'Draft')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          custom_payload: |
            { 
              "attachments": [
                {
                  "color": "#f2c744",
                  "blocks": [
                    {
                        "type": "section",
                        "text": {
                          "type": "plain_text",
                          "emoji": true,

                          "text": "새로운 PR이 등록 되었어요🤗"
                        }
                    },
                     {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": `${process.env.AS_PULL_REQUEST}`
                      },
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",                            
                          "text": "*프로젝트*\n*NEX*"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Source*\n${{ github.head_ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Target*\n${{ github.event.pull_request.base.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*작성자*\n${{ github.event.pull_request.user.login }}"
                        },
                      ]
                    }
                  ]
                }
              ] 
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
  ImmediatelyMERGE:
    if: "contains(github.event.pull_request.title , 'Draft')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          custom_payload: |
            { 
              "attachments": [
                {
                  "color": "#FF0000",
                  "blocks": [
                    {
                        "type": "section",
                        "text": {
                          "type": "plain_text",
                          "emoji": true,

                          "text": "🚨리뷰없이 MERGE 됩니다."
                        }
                    },
                     {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": `${process.env.AS_PULL_REQUEST}`
                      },
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",                            
                          "text": "*프로젝트*\n*NEX*"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Source*\n${{ github.head_ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Target*\n${{ github.event.pull_request.base.ref }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*작성자*\n${{ github.event.pull_request.user.login }}"
                        },
                      ]
                    }
                  ]
                }
              ] 
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
