name: '[test]'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: where am i?
        run: pwd

      - name: hi?
        run: pwd

      - name: Check GITHUB_WORKSPACE
        run: echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
