name: '[test]'

on:
  push: 
     branches:
      - 'main'

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          
      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build
