name: '[test]'

on:
  push: 
     branches:
      - 'develop'

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
          
      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build:standalone

      - name: Change Build Directory
        run: |
          TARGET_DIR='.next_real'

          if [ -d $TARGET_DIR ]
          then
            rm -rf $TARGET_DIR
          fi

          mv .next $TARGET_DIR

      - name: Start or Reload Server
        run: pm2 startOrReload ecosystem.config.js --update-env
