name: '[PIK-Swap] 55번 개발 서버 배포'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-develop:
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
          
      - uses: actions/checkout@v2
        with:
          clean: false

      - run: echo ${{ github.workspace }}
          
      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Change Build Directory
        run: |
          TARGET_DIR='.next_real'

          if [ -d $TARGET_DIR ]
          then
            rm -rf $TARGET_DIR
          fi

          mv .next $TARGET_DIR

      - name: Start or Reload Server
        run: pm2 startOrReload ecosystem.config.js --update-env
